# adapted from workshop-template-b, evanwill
# https://github.com/evanwill/workshop-template-b
# A Jekyll template for a simple workshop website

# Site settings
# title appears in the header
title: data wrangling intro
# title-icon appears in the header to give some pizazz (leave blank for none)
# choose from Font Awesome 5 free, https://fontawesome.com/icons?d=gallery&m=free
# some options: fas fa-wrench; fas fa-cogs; fas fa-code; fas fa-chalkboard-teacher; fas fa-book-open
title-icon: 
# description and keywords for meta tags
description: "A workshop for learning basic data wrangling skills"
keywords: "OpenRefine, data, data wrangling, data cleaning, workshop"
featured-image: "/images/GC_Campus_LM-3181.jpg"

# author settings for cc-by, appears in the footer
author: Sharron Stapleton
pub_year: 2020
github_username: stapletonsl
# Need to add acknowledgement to Evan Wills

# add the full url for the github repository
repo: "https://github.com/GriffithUniLibrary/intro-data-wrangle/"

# site urls
# add the url for the domain,
# on gh-pages follow the pattern: https://username.github.io 
url: https://GriffithUniLibrary.github.io
# add subsection of the domain,
# on gh-pages this is a / followed by the name of the repository
baseurl: /intro-data-wrangle
# add search box to footer?
search: true

# add google analytics if desired (optional)
# if blank, it will be ignored
# use JEKYLL_ENV=production on build command
google_analytics: UA-166331172-1

# defaults (to simplify front matter)
defaults:
  - scope:
      path: "content"
    values:
      layout: "default"
# Build settings
markdown: kramdown
